
import { gql, GraphQLClient } from 'graphql-request';
import Head from 'next/head'
import HomeSection from '../components/HomeSection';

export default function Home({homepage}) {
  return (
    <div>
      <Head>
        <title>Croner datoCMS test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
         {homepage.homepageDetail.map(section => <HomeSection details={section} key={section.id} />)}
      </div>
    </div>
  )
}

const query = gql`
  query {
    homepage {
      id
      name
      slug
      homepageDetail {
        ... on LandingPageRecord {
          __typename
          bigTitleH1
          subtitleH2
          image {
            url
          }
          firstButton
          secondButton
          id
        }
      }
    }
  }
`;

export async function getStaticProps () {
   const endpoint = "https://graphql.datocms.com";
   const graphQLClient = new GraphQLClient(endpoint, {
      headers: {
         "content-type": "application/json",
         authorization: "Bearer " + process.env.DATOCMS_API_KEY
      }
   });
   const course = await graphQLClient.request(query);
   return {
      props: course
   }
}